/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#105aaf",
        "on-primary-container": "#002450",
        "surface-dim": "#cdd1ff",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "secondary-container": "#81f3e5",
        "outline-variant": "#a5aad7",
        "on-primary": "#eff2ff",
        "primary": "#105aaf",
        "error": "#b31b25",
        "outline": "#6f749e",
        "tertiary-dim": "#624d00",
        "on-surface-variant": "#535981",
        "on-background": "#262c51",
        "secondary-fixed": "#81f3e5",
        "on-tertiary-fixed-variant": "#675200",
        "primary-fixed-dim": "#5e96ee",
        "background": "#f7f5ff",
        "tertiary-fixed-dim": "#eec540",
        "secondary-fixed-dim": "#72e4d7",
        "tertiary": "#705900",
        "tertiary-fixed": "#fdd34d",
        "surface-container-high": "#dee0ff",
        "on-secondary-container": "#005a53",
        "on-secondary-fixed-variant": "#00655d",
        "surface": "#f7f5ff",
        "inverse-surface": "#040a2f",
        "primary-fixed": "#6ca3fd",
        "on-secondary-fixed": "#004640",
        "on-secondary": "#bffff5",
        "secondary-dim": "#005a53",
        "surface-container-lowest": "#ffffff",
        "error-dim": "#9f0519",
        "inverse-primary": "#6ca3fd",
        "surface-container": "#e6e6ff",
        "on-tertiary": "#fff2d4",
        "surface-variant": "#d7daff",
        "on-surface": "#262c51",
        "on-tertiary-fixed": "#463600",
        "on-primary-fixed-variant": "#002e60",
        "primary-container": "#6ca3fd",
        "surface-container-highest": "#d7daff",
        "primary-dim": "#004e9d",
        "secondary": "#00675f",
        "surface-bright": "#f7f5ff",
        "error-container": "#fb5151",
        "tertiary-container": "#fdd34d",
        "on-tertiary-container": "#5c4900",
        "on-primary-fixed": "#000002",
        "inverse-on-surface": "#959ac6",
        "surface-container-low": "#f0efff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
